services:
  fuseki:
    image: stain/jena-fuseki
    platform: linux/amd64
    container_name: fuseki-H2
    ports:
      - "3032:3030"
    environment:
      - ADMIN_PASSWORD=admin
      # Auto-crée un dataset "dataset" (en mémoire)
      - FUSEKI_DATASET_2=dataset
      - FUSEKI_DATASET_2_TYPE=mem
    networks:
      - hospital2-net


  proxy:
    build:
      context: ../../Proxy
      dockerfile: Dockerfile
    container_name: proxy2
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - PROXY_MODE=HOSPITAL
      # Variables spécifiques au mode HOSPITAL
      - PUBLIC_ISSUER=http://localhost:8080/realms/myrealm
      - JWKS_URI=http://keycloak:8080/realms/myrealm/protocol/openid-connect/certs
      - FUSEKI_URL=http://fuseki:3030/dataset/query
    volumes:
      - ../../Proxy/proxy.js:/app/proxy.js
    depends_on:
      - fuseki

    networks:
      - hospital2-net
      - gestionlogiciel_default

  h2-loader:
    image: curlimages/curl:8.7.1
    container_name: h2-loader
    depends_on:
      - fuseki
    command: ["/bin/sh", "-c", "/loader/loader.sh"]
    volumes:
      - ./data:/data:ro
      - ./loader.sh:/loader/loader.sh:ro
    environment:
      - FUSEKI_URL=http://fuseki:3030          # <-- utilise "fuseki" (service), pas container_name
      - DATA_FILE=/data/h2.ttl
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
    networks:
      - hospital2-net

networks:
  hospital2-net:
    driver: bridge
  gestionlogiciel_default:
    external: true
