services:
  keycloak-h1:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-h1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ../../Data/config/hospital1Keycloak:/opt/keycloak/data/import
    ports:
      - "8081:8080"
    restart: always
    networks:
      - hospital-net
      - gestionlogiciel_default

  fuseki:
    image: stain/jena-fuseki
    platform: linux/amd64
    container_name: fuseki-H1
    ports:
      - "3031:3030"
    environment:
      - ADMIN_PASSWORD=admin
      # Auto-crée un dataset "dataset" (en mémoire)
      - FUSEKI_DATASET_1=dataset
      - FUSEKI_DATASET_1_TYPE=mem
    networks:
      - hospital-net


  proxy:
    build:
      context: ../../Proxy
      dockerfile: Dockerfile
    container_name: proxy1
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - PROXY_MODE=HOSPITAL
      # Variables spécifiques au mode HOSPITAL
      - PUBLIC_ISSUER=http://localhost:8080/realms/myrealm
      - JWKS_URI=http://keycloak-central:8080/realms/myrealm/protocol/openid-connect/certs
      - FUSEKI_URL=http://fuseki:3030/dataset/sparql
      # Variables pour le Keycloak local (token exchange)
      - LOCAL_KEYCLOAK_URL=http://keycloak-h1:8080
      - LOCAL_REALM=hospital1-realm
      - LOCAL_CLIENT_ID=hospital-proxy
      - LOCAL_CLIENT_SECRET=hospital1-secret
    volumes:
      - ../../Proxy/proxy.js:/app/proxy.js
    depends_on:
      - fuseki
      - keycloak-h1

    networks:
      - hospital-net
      - gestionlogiciel_default

  h1-loader:
    image: curlimages/curl:8.7.1
    container_name: h1-loader
    depends_on:
      - fuseki
    command: ["/bin/sh", "-c", "/loader/loader.sh"]
    volumes:
      - ./data:/data:ro
      - ./loader.sh:/loader/loader.sh:ro
    environment:
      - FUSEKI_URL=http://fuseki:3030          # <-- utilise "fuseki" (service), pas container_name
      - DATA_FILE=/data/h1.ttl
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
    networks:
      - hospital-net

networks:
  hospital-net:
    driver: bridge
  gestionlogiciel_default:
    external: true