PREFIX ex: <http://example.org/schema#>
PREFIX res: <http://example.org/resource/>

SELECT ?p ?age ?aneu WHERE {
  ?p a ex:Patient ;
     ex:partOf res:study_A ;
     ex:hasAge ?age ;
     ex:hasAneurysm ?aneu .
}