PREFIX ex: <http://example.org/schema#>
PREFIX res: <http://example.org/resource/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?patient ?age ?image
WHERE {
  ?patient a ex:Patient ;
           ex:partOf res:study_A ;
           ex:hasAge ?age ;
           ex:hasImage ?image .

  FILTER(xsd:integer(?age) < 50)
}